### ISSUE TITLE
How to implement loading progress bar at bottom with this library?

### ISSUE THREAD

**Issue by droid-wise** [CardinalNow/android-sectioned-adapter#2]

**Comment by axemorgan** [comment]
If you're asking for a way to implement endless scrolling, that's a bit out of scope for what this library provides.  Codepath has an excellent guide for how you can do endless scrolling here (see the Implementing with RecyclerView section: 
[https://github.com/codepath/android_guides/wiki/Endless-Scrolling-with-AdapterViews-and-RecyclerView](https://github.com/codepath/android_guides/wiki/Endless-Scrolling-with-AdapterViews-and-RecyclerView)
